s=set()
n=int(input("input number 1: "))
s.add(n)
n=int(input("input number 2: "))
s.add(n)
n=int(input("input number 3: "))
s.add(n)
n=int(input("input number 4: "))
s.add(n)
n=int(input("input number 5: "))
s.add(n)
n=int(input("input number 6: "))
s.add(n)
n=int(input("input number 7: "))
s.add(n)
print (s)